import { chromium } from "playwright";
import http from "node:http"; import fs from "node:fs"; import path from "node:path";
const SITE = process.argv[2], SHOT = SITE + "/../";
const srv = http.createServer((q,r)=>{const f=path.join(SITE,q.url==="/"?"index.html":q.url.split("?")[0]);
  fs.readFile(f,(e,d)=>{if(e){r.writeHead(404);return r.end("404");}
  r.writeHead(200,{"content-type":f.endsWith(".js")?"text/javascript":"text/html; charset=utf-8"});r.end(d);});});
await new Promise(r=>srv.listen(4330,r));
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1360, height: 950 } });
const errs=[]; page.on("pageerror",e=>errs.push("pageerror: "+e.message));
page.on("console",m=>{if(m.type()==="error")errs.push("console: "+m.text().slice(0,140));});
await page.goto("http://localhost:4330/", { waitUntil: "networkidle" });
await page.waitForTimeout(700);
await page.locator("input").nth(0).fill("10203");
await page.locator("input").nth(1).fill("테스트");
await page.locator("input").nth(2).fill("1234");
await page.getByRole("button", { name: "기록실 입장", exact: true }).first().click();
await page.waitForTimeout(1400);
const before = (await page.locator("body").innerText()).replace(/\s+/g," ");
const T = "이 유물은 오랫동안 사용된 흔적을 지니고 있으며, 그 흔적은 사용자의 반복된 동작과 생활의 조건을 보여 준다. 첫째, 표면의 마모가 한쪽에만 집중되어 있다.";
console.log("입장 후:", before.slice(0,160));
const nAreas = await page.locator("[data-fk] textarea").count();
console.log("data-fk textarea", nAreas, "· 전체 textarea", await page.locator("textarea").count(), "· data-fk 요소", await page.locator("[data-fk]").count());
const cell = page.locator("[data-fk] textarea").first();
await cell.click();
await page.evaluate((t)=>{const el=document.activeElement;const dt=new DataTransfer();dt.setData("text",t);
  el.dispatchEvent(new ClipboardEvent("paste",{clipboardData:dt,bubbles:true,cancelable:true}));
  Object.getOwnPropertyDescriptor(window.HTMLTextAreaElement.prototype,"value").set.call(el, el.value+t);
  el.dispatchEvent(new Event("input",{bubbles:true}));}, T);
await page.waitForTimeout(1600);
const after = (await page.locator("body").innerText()).replace(/\s+/g," ");
const cues = ["어디에서 왔나요","가져온 문장","그대로","되돌아보기","전유","붙여넣기"];
console.log("학생 화면에 남은 단서:", cues.filter(c=>after.includes(c)).join(" / ") || "없음");
const added = after.replace(before.slice(0,80),"").length - before.length;
console.log("붙여넣은 글 자체 외에 늘어난 화면 글자:", Math.max(0, after.length - before.length - T.length), "자 (0에 가까워야)");
const rec = await page.evaluate(()=>((window.__probeMem["ws:10203"]||{})._paste||[]));
console.log("기록된 것:", JSON.stringify(rec.map(e=>({k:e.k,n:e.n,b:e.b,base:e.base,src:e.src===undefined?"(없음)":e.src}))));
await page.screenshot({ path: SHOT + "shot-q-student.png" });
console.log("오류:", errs.length?errs.slice(0,4):"없음");
await browser.close(); srv.close();
